name: Java CI/CD Pipeline

on:
  push:
    branches: [ "main", "desenvolvimento" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Localizar e Compilar Java
      # Este comando procura qualquer arquivo .java no repositório e compila
      run: |
        find . -name "*.java" > java_files.txt
        if [ -s java_files.txt ]; then
          javac $(cat java_files.txt)
          echo "Sucesso: Arquivos Java compilados."
        else
          echo "Erro: Nenhum arquivo Java encontrado no repositório!"
          exit 1
        fi

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Simulating Continuous Deployment
      run: echo "Deploy executado com sucesso no servidor!"

  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar Notificação
        uses: appleboy/discord-action@master
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          message: "O deploy foi concluído com sucesso! ✅"